# Generated by Django 2.2 on 2020-09-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_vehicleowns'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleOwns',
        ),
    ]
