# Generated by Django 2.2 on 2020-09-12 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default=' ', max_length=50)),
                ('model', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('VIN_number', models.CharField(blank=True, default='00000', max_length=50, null=True)),
                ('date_of_purchase', models.DateField(blank=True, null=True, default=timezone.now())),
                ('date_of_last_service', models.DateField(blank=True, null=True, default=timezone.now())),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
