# Generated by Django 2.2 on 2020-09-12 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclesown', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowned',
            name='date_of_last_service',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 12, 22, 45, 47, 807121, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vehicleowned',
            name='date_of_purchase',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 12, 22, 45, 47, 807121, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vehicleowned',
            name='make',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicleowned',
            name='model',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
